import type { Metadata } from 'next';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white h-screen">
          <div className="relative">
            <div className="mx-auto max-w-7xl">
              <div className="relative z-10 pt-14 h-screen lg:w-full lg:max-w-2xl">
                <svg
                  className="absolute inset-y-0 right-8 hidden h-screen w-80 translate-x-1/2 transform fill-white lg:block"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="none"
                  aria-hidden="true"
                >
                  <polygon points="0,0 90,0 50,100 0,100" />
                </svg>
                <div className="relative px-6 lg:pt-8 py-0 lg:px-8 lg:py-56 lg:pr-0">
                  {children}
                </div>
              </div>
            </div>
            <div className="bg-gray-50 hidden lg:block lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
              <Image
                className="aspect-[3/2] object-cover lg:aspect-auto lg:h-full lg:w-full"
                src="https://images.unsplash.com/photo-1598791318878-10e76d178023?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                alt="a picture with a todo list"
                width="0"
                height="0"
                sizes="100vw"
              />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
